/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pakg1.automated_Meal_counter;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Tammum Islam
 */
public class UpdatingMeal extends javax.swing.JFrame {

    /**
     * Creates new form UpdatingMeal
     */
    public UpdatingMeal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UpdatingIdTextBox = new javax.swing.JTextField();
        UpdatingDateTextBox = new javax.swing.JTextField();
        UpdatingMealTextBox = new javax.swing.JTextField();
        MealUpdating = new javax.swing.JButton();
        UpdateClear = new javax.swing.JButton();
        gotoUpdateMeal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id :");

        jLabel2.setText("Date :");

        jLabel3.setText("Number of Meal :");

        MealUpdating.setText("Update");
        MealUpdating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealUpdatingActionPerformed(evt);
            }
        });

        UpdateClear.setText("Clear");
        UpdateClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateClearActionPerformed(evt);
            }
        });

        gotoUpdateMeal.setText("Back");
        gotoUpdateMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoUpdateMealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MealUpdating)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdatingIdTextBox)
                            .addComponent(UpdatingDateTextBox)
                            .addComponent(UpdatingMealTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(UpdateClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(gotoUpdateMeal)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdatingIdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UpdatingDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdatingMealTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MealUpdating)
                    .addComponent(UpdateClear)
                    .addComponent(gotoUpdateMeal))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotoUpdateMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoUpdateMealActionPerformed
        // TODO add your handling code here:
        //going back to adminsection
         AdminSection adminsection = new AdminSection();
        adminsection.setVisible(true);
        adminsection.setLocation(450,150);
        this.dispose();
    }//GEN-LAST:event_gotoUpdateMealActionPerformed

    private void UpdateClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateClearActionPerformed
        // TODO add your handling code here:
        //clearing for new update
        UpdatingIdTextBox.setText("");
        UpdatingDateTextBox.setText("");
        UpdatingMealTextBox.setText("");
    }//GEN-LAST:event_UpdateClearActionPerformed

    private void MealUpdatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealUpdatingActionPerformed
        // TODO add your handling code here:
        //updating the meal
        int status = 0;
        
        try{
            String id = UpdatingIdTextBox.getText();
            String date = UpdatingDateTextBox.getText();
            String mealcount = UpdatingMealTextBox.getText();
           
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/mealcounter","tam1","ce13030");
            JOptionPane.showMessageDialog(this, "database connection successful");
            PreparedStatement ps=con.prepareStatement("insert into meals(ids,date,numberofmeal) values(?,?,?)");
		ps.setString(1,id);
		ps.setString(2,date);
		ps.setString(3,mealcount);
		status = ps.executeUpdate();
                if(status>0){
                    JOptionPane.showMessageDialog(this, "Meal update successful");
                    status = 0;
                }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "database connection failed");
        }
    }//GEN-LAST:event_MealUpdatingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatingMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatingMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatingMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatingMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatingMeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MealUpdating;
    private javax.swing.JButton UpdateClear;
    private javax.swing.JTextField UpdatingDateTextBox;
    private javax.swing.JTextField UpdatingIdTextBox;
    private javax.swing.JTextField UpdatingMealTextBox;
    private javax.swing.JButton gotoUpdateMeal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
